COLUMNS:
  age: float64
  sex: int64
  cp: int64
  trestbps: float64
  chol: float64
  fbs: int64
  restecg: int64
  thalach: float64
  exang: int64
  oldpeak: float64
  slope: int64
  ca: int64
  thal: int64
  target: int64

TARGET_COLUMN:
  name: target
